### ISSUE TITLE
Client-provided username is not used

### ISSUE THREAD

**Issue by gavllew** [linuxwolf/sazzle#1]
Maybe I'm not understanding the server-side usage correctly - please correct me if I'm missing something.

There's a username string/callback provided via the config - if this is defined then the client-provided value must match.  I'm not providing it, so I expect things to proceed using the client-provided username.  However, then the password callback is run with an undefined username parameter, so my password lookup fails.  It looks like this will only work if the server supplies a username...

**Comment by linuxwolf** [comment]
I assume this is in the PLAIN mechanism?

Yes, it does look like it's ignoring the client-provided username when calling into your application code.  I'll get that fixed soon.

**Comment by gavllew** [comment]
My testing so far has been with PLAIN, but inspection of the SCRAM-SHA1 code suggests that the same problem would arise.

**Comment by gavllew** [comment]
Note that the above changes attempt to fix both mechanisms, but I've only done any testing on the PLAIN mechanism.

**Comment by linuxwolf** [comment]
The changes look good, and pass some tests I wrote to prepare to fix this myself!  Submit a pull-request and I can get this merged in.

Thanks!
